#!/usr/bin/env node
// GENERATED by scripts/build-shims.mjs from src/hooks/guard-rules.ts — do not edit by hand.
// Edit the template in shims/templates/ or the rule table, then run: npm run shims
// MaaawKit PreToolUse guard shim — zero dependencies, graceful enhancement.
// With the maaawkit engine installed: config-aware guard (levels, custom rules).
// Without it: embedded fallback compiled from the same rule table (2.6 behavior).
// Contract: JSON decision on stdout, exit 0 always (never break the session).

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf-8");
}

const raw = await readStdin();

try {
  const { runHook } = await import("maaawkit/hooks");
  const { stdout } = await runHook("guard", raw);
  if (stdout) process.stdout.write(stdout);
  process.exit(0);
} catch (error) {
  let localEngineExists = false;
  try {
    const { existsSync } = await import("node:fs");
    localEngineExists = existsSync(new URL("./node_modules/maaawkit", import.meta.url));
  } catch {
    localEngineExists = false;
  }
  if (localEngineExists) {
    const message = error instanceof Error ? error.message : String(error);
    emit("deny", `MaaawKit engine guard failed; refusing instead of falling back: ${message}`);
  }
  // Engine not installed — embedded fallback below.
}

const FALLBACK = {
  "bashRules": [
    {
      "pattern": "\\brm\\s+(?=[^;&|]*(?:-[a-zA-Z]*[rf][a-zA-Z]*|--recursive|--force|--no-preserve-root)\\b)[^;&|]*?\\s['\"]?(?:/(?:\\*+)?|~[/\\\\]?|(?:\\$HOME|\\$\\{HOME\\})[/\\\\]?|/(?:etc|usr|var|bin|sbin|lib|lib64|boot|sys|proc|dev|root|home|opt)(?:/\\*?|/)?)['\"]?(?=\\s|$)",
      "flags": "",
      "message": "Refusing recursive delete of root/home/system paths. Target a specific safe path instead.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+push(?!.*--force-with-lease)(?=.*(\\s--force\\b|\\s-f\\b))",
      "flags": "",
      "message": "Force push blocked. Use --force-with-lease, and only on feature branches.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+push\\b(?=.*\\s\\+\\S+)",
      "flags": "",
      "message": "Force-push refspecs with leading + are blocked. Use --force-with-lease explicitly.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+reset\\s+--hard\\b",
      "flags": "",
      "message": "git reset --hard discards work. Confirm with user or use git stash.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+clean\\s+-[a-zA-Z]*f",
      "flags": "",
      "message": "git clean -f deletes untracked files permanently.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+checkout\\s+\\.\\s*$|\\bgit\\s+restore\\s+\\.\\s*$",
      "flags": "",
      "message": "Discarding ALL uncommitted changes — confirm intended.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bdd\\s+.*\\bof=/dev/",
      "flags": "",
      "message": "Writing directly to device is blocked.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bmkfs\\.|(?:^|[;&|]\\s*)(format(\\.com)?)\\s+[a-zA-Z]:",
      "flags": "",
      "message": "Filesystem format commands are blocked.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bdrop\\s+(database|table)\\b",
      "flags": "i",
      "message": "DROP DATABASE/TABLE — needs explicit user confirmation.",
      "action": "ask",
      "sql": true
    },
    {
      "pattern": "\\btruncate\\s+table\\b",
      "flags": "i",
      "message": "TRUNCATE TABLE — needs explicit user confirmation.",
      "action": "ask",
      "sql": true
    },
    {
      "pattern": "(?=.*\\bRemove-Item\\b)(?=.*-Recurse\\b)(?=.*-Force\\b)(?=.*(\\s[a-zA-Z]:\\\\?(\\s|$|['\"])|\\$env:USERPROFILE|\\$HOME\\b|\\s~[/\\\\]?(\\s|$)))",
      "flags": "i",
      "message": "Refusing recursive force-delete of drive root or user profile.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+push\\s+.*--mirror\\b",
      "flags": "",
      "message": "git push --mirror overwrites remote wholesale. Blocked.",
      "action": "deny",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+branch\\s+(-D|--delete\\s+--force)\\b",
      "flags": "",
      "message": "Force-deleting branch discards unmerged work.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bgit\\s+tag\\s+(-d|--delete)\\b",
      "flags": "",
      "message": "Deleting tags — confirm intent.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bdocker\\s+system\\s+prune\\b|\\bdocker\\s+(image|container|volume)\\s+prune\\b",
      "flags": "",
      "message": "Docker prune removes data broadly.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bkubectl\\s+delete\\b",
      "flags": "",
      "message": "kubectl delete against live cluster — confirm target context.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\baz\\s+(group|resource)\\s+delete\\b|\\baz\\s+deployment\\s+group\\s+delete\\b|\\baz\\s+keyvault\\s+secret\\s+delete\\b|\\baz\\s+storage\\s+container\\s+delete\\b|\\bgcloud\\s+projects\\s+delete\\b|\\baws\\s+s3\\s+rb\\b",
      "flags": "",
      "message": "Cloud resource/resource-group/bucket deletion — needs explicit approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bterraform\\s+destroy\\b|\\bpulumi\\s+destroy\\b",
      "flags": "",
      "message": "Infrastructure destroy — needs explicit approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "(?:curl|wget)\\s+[^|]*\\|\\s*(?:sudo\\s+)?(?:(?:ba|z|k|da)?sh|fish)\\b|irm\\s+[^|]*\\|\\s*iex|iwr\\s+[^|]*\\|\\s*iex",
      "flags": "",
      "message": "Piping remote scripts to shell — needs explicit user approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "(?:>|>>)\\s*(?:\\.env(?:\\.[\\w.]+)?|[^\\s;&|]+[/\\\\]\\.env(?:\\.[\\w.]+)?)(?=\\s|$|[;&|])",
      "flags": "",
      "message": "Shell redirection to .env (secrets) needs explicit user approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "(?:>|>>)\\s*(?:id_rsa|id_ed25519|[^\\s;&|]+\\.(?:pem|pfx|key))(?=\\s|$|[;&|])",
      "flags": "",
      "message": "Shell redirection to private key material needs explicit user approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\btee\\s+(?:-a\\s+)?(?:\\.env(?:\\.[\\w.]+)?|[^\\s;&|]+[/\\\\]\\.env(?:\\.[\\w.]+)?|id_rsa|id_ed25519|[^\\s;&|]+\\.(?:pem|pfx|key))(?=\\s|$|[;&|])",
      "flags": "",
      "message": "Writing secrets/keys via tee — needs explicit user approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bgh\\s+repo\\s+delete\\b|\\bgh\\s+release\\s+delete\\b|\\bgh\\s+api\\b(?=.*\\s-X\\s+DELETE\\b)",
      "flags": "",
      "message": "GitHub destructive operation — needs explicit approval.",
      "action": "ask",
      "sql": false
    },
    {
      "pattern": "\\bnpm\\s+publish\\b|\\bdotnet\\s+nuget\\s+push\\b|\\btwine\\s+upload\\b",
      "flags": "i",
      "message": "Publishing packages needs explicit user approval.",
      "action": "ask",
      "sql": false
    }
  ],
  "writeRules": [
    {
      "pattern": "(^|[/\\\\])\\.env(\\.[\\w.]+)?$",
      "flags": "",
      "message": "Writing to .env (secrets). Confirm with user."
    },
    {
      "pattern": "(^|[/\\\\])(id_rsa|id_ed25519|.*\\.pem|.*\\.pfx|.*\\.key)$",
      "flags": "",
      "message": "Writing to a private key file."
    },
    {
      "pattern": "(^|[/\\\\])appsettings\\.Production\\.json$",
      "flags": "",
      "message": "Editing PRODUCTION appsettings. Confirm first."
    },
    {
      "pattern": "(^|[/\\\\])\\.git[/\\\\]",
      "flags": "",
      "message": "Direct writes inside .git/ are blocked."
    }
  ],
  "textish": "^\\s*(git\\s+(commit|tag)|echo|printf)\\b"
};

function emit(decision, reason) {
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: decision,
        permissionDecisionReason: reason,
      },
    }),
  );
  process.exit(0);
}

let data = {};
try {
  data = JSON.parse(raw) || {};
} catch {
  process.exit(0);
}
const tool = data.tool_name || "";
const toolInput = data.tool_input || {};

if (tool === "Bash" || tool === "PowerShell") {
  const cmd = typeof toolInput.command === "string" ? toolInput.command : "";
  const textish = new RegExp(FALLBACK.textish).test(cmd);
  for (const rule of FALLBACK.bashRules) {
    if (textish && rule.sql) continue;
    if (new RegExp(rule.pattern, rule.flags).test(cmd)) emit(rule.action, rule.message);
  }
} else if (tool === "Edit" || tool === "Write" || tool === "MultiEdit" || tool === "NotebookEdit") {
  const path = toolInput.file_path || toolInput.path || "";
  for (const rule of FALLBACK.writeRules) {
    if (new RegExp(rule.pattern, rule.flags).test(path)) emit("ask", rule.message);
  }
}
process.exit(0);
