/**
 * Shim generation: compiles the canonical guard rule table into the
 * hand-written shim templates. The committed shims/*.mjs files are generated
 * artifacts; a drift test regenerates them from src and fails on mismatch,
 * which is what makes "fallback can never drift from the engine" a checked
 * property instead of a promise.
 */

import { BASH_RULES, PROTECTED_WRITE_RULES, TEXTISH_COMMAND } from "./guard-rules.js";

export const FALLBACK_PLACEHOLDER = "/*__MAAAW_FALLBACK_DATA__*/";
export const GENERATED_HEADER =
  "// GENERATED by scripts/build-shims.mjs from src/hooks/guard-rules.ts — do not edit by hand.\n" +
  "// Edit the template in shims/templates/ or the rule table, then run: npm run shims\n";

/** The data blob embedded into shims that need the guard rules. */
export function fallbackDataLiteral(): string {
  const data = {
    bashRules: BASH_RULES.map((r) => ({
      pattern: r.pattern,
      flags: r.flags,
      message: r.message,
      action: r.action,
      sql: r.category === "sql",
    })),
    writeRules: PROTECTED_WRITE_RULES.map((r) => ({
      pattern: r.pattern,
      flags: r.flags,
      message: r.message,
    })),
    textish: TEXTISH_COMMAND,
  };
  return `const FALLBACK = ${JSON.stringify(data, null, 2)};`;
}

/** Render a template into the final committed shim content. */
export function generateShim(template: string): string {
  const body = template.includes(FALLBACK_PLACEHOLDER)
    ? template.replace(FALLBACK_PLACEHOLDER, fallbackDataLiteral())
    : template;
  // The shebang must stay on line 1; the generated-file header goes after it.
  if (body.startsWith("#!")) {
    const nl = body.indexOf("\n");
    return `${body.slice(0, nl + 1)}${GENERATED_HEADER}${body.slice(nl + 1)}`;
  }
  return GENERATED_HEADER + body;
}
